#!/usr/bin/env python3
"""Generate a KTH-source-aligned train/validation smoke dataset.

This is a newly declared replacement experiment, not a historical recovery.
The building-disjoint test source IDs are frozen but no test samples or test
outcomes are generated by this script.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

PACKAGE_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(PACKAGE_ROOT))

from generate_floorplan_dataset import (  # noqa: E402
    GenerationConfig,
    assign_splits,
    discover_floorplans,
    ray_offsets,
    scan_from_pose,
    select_navigable_component,
)
from mso_recovery.common import sha256_file, stable_seed, write_json  # noqa: E402


STATUS = "new_kth_source_aligned_smoke_not_historical_recovery"


@dataclass(frozen=True)
class SmokeConfig:
    pixels_per_meter: int = 16
    working_resolution_m_per_cell: float = 0.0625
    physical_window_m: int = 30
    raw_size: int = 480
    model_size: int = 256
    sensor_range_m: int = 15
    laser_range_cells: int = 240
    laser_rays: int = 360
    actions_before_capture: int = 14
    forward_step_m: float = 1.0
    forward_step_cells: int = 16
    turn_degrees: int = 30
    source_obstacle_dilation_iterations: int = 3
    observation_known_dilation_iterations: int = 1
    content_padding_source_cells: int = 8
    samples_per_floorplan: int = 4
    maximum_attempts_per_floorplan: int = 160
    split_seed: int = 20260807
    generation_seed: int = 20260807
    minimum_observed_obstacle_fraction: float = 0.0125
    minimum_observed_free_fraction: float = 0.10
    maximum_free_to_obstacle_ratio: float = 25.0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--samples-per-floorplan", type=int, default=4)
    parser.add_argument("--maximum-attempts-per-floorplan", type=int, default=160)
    parser.add_argument("--seed", type=int, default=20260807)
    return parser.parse_args()


def load_source_occupied(record: dict[str, object], config: SmokeConfig) -> np.ndarray:
    gray = np.asarray(Image.open(Path(record["gt_path"])).convert("L"), dtype=np.uint8)
    occupied = gray < 128
    content = occupied if float(occupied.mean()) < 0.5 else ~occupied
    ys, xs = np.where(content)
    if not len(ys):
        raise ValueError(f"No content in {record['floorplan_id']}")
    pad = config.content_padding_source_cells
    y0 = max(0, int(ys.min()) - pad)
    y1 = min(gray.shape[0], int(ys.max()) + pad + 1)
    x0 = max(0, int(xs.min()) - pad)
    x1 = min(gray.shape[1], int(xs.max()) + pad + 1)
    occupied = occupied[y0:y1, x0:x1]
    source_resolution = float(record["resolution_m_per_cell"])
    scale = source_resolution / config.working_resolution_m_per_cell
    occupied = cv2.resize(
        occupied.astype(np.uint8),
        (
            max(8, int(round(occupied.shape[1] * scale))),
            max(8, int(round(occupied.shape[0] * scale))),
        ),
        interpolation=cv2.INTER_NEAREST,
    ).astype(bool)
    occupied[[0, -1], :] = True
    occupied[:, [0, -1]] = True
    occupied = cv2.dilate(
        occupied.astype(np.uint8),
        np.ones((3, 3), np.uint8),
        iterations=config.source_obstacle_dilation_iterations,
    ).astype(bool)
    outer_pad = config.raw_size + config.laser_range_cells + 8
    return np.pad(occupied, outer_pad, mode="constant", constant_values=True)


def restricted_starts(component: np.ndarray) -> np.ndarray:
    clearance = cv2.distanceTransform(component.astype(np.uint8), cv2.DIST_L2, 5)
    ys, xs = np.where(component)
    y0, y1 = int(ys.min()), int(ys.max()) + 1
    x0, x1 = int(xs.min()), int(xs.max()) + 1
    bbox_mask = np.zeros(component.shape, dtype=bool)
    bbox_mask[
        y0 + int(0.10 * (y1 - y0)) : y0 + int(0.80 * (y1 - y0)),
        x0 + int(0.10 * (x1 - x0)) : x0 + int(0.80 * (x1 - x0)),
    ] = True
    starts = np.argwhere((clearance >= 2.0) & bbox_mask)
    if not len(starts):
        starts = np.argwhere(component & bbox_mask)
    if not len(starts):
        raise ValueError("No navigable start in the declared 10--80% box")
    return starts


def action_for_step(step: int, rng: np.random.Generator) -> int:
    if step > 5 and step not in {7, 9, 11, 13}:
        return int(rng.integers(1, 3))
    return 0


def attempt_forward(
    pose: np.ndarray, heading: float, component: np.ndarray, cells: int
) -> np.ndarray:
    current = pose.copy()
    for distance in range(1, cells + 1):
        candidate = np.asarray(
            [
                int(round(pose[0] - math.sin(heading) * distance)),
                int(round(pose[1] + math.cos(heading) * distance)),
            ],
            dtype=np.int32,
        )
        if not component[int(candidate[0]), int(candidate[1])]:
            break
        current = candidate
    return current


def oriented_crop(
    array: np.ndarray,
    pose: np.ndarray,
    heading: float,
    size: int,
    border_value: int | float,
) -> np.ndarray:
    patch_size = int(math.ceil(size * math.sqrt(2.0))) + 4
    if patch_size % 2:
        patch_size += 1
    half = patch_size // 2
    y, x = int(pose[0]), int(pose[1])
    patch = array[y - half : y + half, x - half : x + half]
    if patch.shape != (patch_size, patch_size):
        raise ValueError(f"Unexpected oriented crop patch: {patch.shape}")
    angle = -heading * 180.0 / math.pi + 90.0
    matrix = cv2.getRotationMatrix2D((half, half), angle, 1.0)
    rotated = cv2.warpAffine(
        patch,
        matrix,
        (patch_size, patch_size),
        flags=cv2.INTER_NEAREST,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=border_value,
    )
    start = (patch_size - size) // 2
    return rotated[start : start + size, start : start + size]


def generate_sample(
    occupied: np.ndarray,
    component: np.ndarray,
    starts: np.ndarray,
    rays: list[tuple[np.ndarray, np.ndarray]],
    rng: np.random.Generator,
    config: SmokeConfig,
) -> tuple[np.ndarray, np.ndarray, dict[str, float]] | None:
    pose = starts[int(rng.integers(0, len(starts)))].astype(np.int32)
    heading = float(rng.random() * 2.0 * math.pi)
    known = np.zeros(occupied.shape, dtype=bool)
    scan_from_pose(occupied, known, pose, rays)
    for step in range(1, config.actions_before_capture + 1):
        action = action_for_step(step, rng)
        if action == 0:
            pose = attempt_forward(
                pose, heading, component, config.forward_step_cells
            )
        elif action == 1:
            heading += math.radians(config.turn_degrees)
        else:
            heading -= math.radians(config.turn_degrees)
        scan_from_pose(occupied, known, pose, rays)
    known = cv2.dilate(
        known.astype(np.uint8),
        np.ones((3, 3), np.uint8),
        iterations=config.observation_known_dilation_iterations,
    ).astype(bool)
    target = oriented_crop(
        occupied.astype(np.uint8), pose, heading, config.raw_size, 1
    ).astype(bool)
    observed = oriented_crop(
        known.astype(np.uint8), pose, heading, config.raw_size, 0
    ).astype(bool)
    observation = np.zeros((config.raw_size, config.raw_size, 3), dtype=np.uint8)
    observation[:, :, 0] = (observed & target).astype(np.uint8) * 255
    observation[:, :, 1] = (~observed).astype(np.uint8) * 255
    observation[:, :, 2] = (observed & ~target).astype(np.uint8) * 255
    obstacle_fraction = float(np.mean(observation[:, :, 0] == 255))
    unknown_fraction = float(np.mean(observation[:, :, 1] == 255))
    free_fraction = float(np.mean(observation[:, :, 2] == 255))
    if obstacle_fraction < config.minimum_observed_obstacle_fraction:
        return None
    if free_fraction < config.minimum_observed_free_fraction:
        return None
    if free_fraction > obstacle_fraction * config.maximum_free_to_obstacle_ratio:
        return None
    return observation, target.astype(np.uint8) * 255, {
        "obstacle_fraction": obstacle_fraction,
        "unknown_fraction": unknown_fraction,
        "free_fraction": free_fraction,
        "target_fraction": float(target.mean()),
    }


def describe(values: list[float]) -> dict[str, float]:
    array = np.asarray(values, dtype=np.float64)
    return {
        "minimum": float(array.min()),
        "p10": float(np.quantile(array, 0.1)),
        "median": float(np.median(array)),
        "p90": float(np.quantile(array, 0.9)),
        "maximum": float(array.max()),
        "global_mean": float(array.mean()),
    }


def main() -> None:
    args = parse_args()
    config = SmokeConfig(
        samples_per_floorplan=args.samples_per_floorplan,
        maximum_attempts_per_floorplan=args.maximum_attempts_per_floorplan,
        generation_seed=args.seed,
    )
    if config.raw_size != config.physical_window_m * config.pixels_per_meter:
        raise ValueError("Window geometry is inconsistent")
    if config.laser_range_cells != config.sensor_range_m * config.pixels_per_meter:
        raise ValueError("Sensor geometry is inconsistent")
    if args.output_root.exists() and any(args.output_root.iterdir()):
        raise FileExistsError(f"Refusing non-empty output: {args.output_root}")
    args.output_root.mkdir(parents=True, exist_ok=True)
    incomplete = args.output_root / "GENERATION_INCOMPLETE"
    incomplete.write_text(STATUS + "\n", encoding="utf-8")

    records = discover_floorplans(args.source_root.resolve())
    assignments = assign_splits(
        records,
        GenerationConfig(split_seed=config.split_seed),
    )
    source_split_path = args.output_root / "source_split.csv"
    source_rows: list[dict[str, object]] = []
    for record in records:
        floorplan_id = str(record["floorplan_id"])
        source_rows.append(
            {
                "floorplan_id": floorplan_id,
                "building_id": record["building_id"],
                "split": assignments[floorplan_id],
                "source_relpath": record["source_relpath"],
                "source_sha256": record["source_sha256"],
                "resolution_m_per_cell": record["resolution_m_per_cell"],
            }
        )
    with source_split_path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(source_rows[0]))
        writer.writeheader()
        writer.writerows(source_rows)
    building_counts = {
        split: len(
            {
                str(row["building_id"])
                for row in source_rows
                if row["split"] == split
            }
        )
        for split in ("train", "val", "test")
    }
    floorplan_counts = {
        split: sum(row["split"] == split for row in source_rows)
        for split in ("train", "val", "test")
    }
    if building_counts != {"train": 102, "val": 22, "test": 22}:
        raise RuntimeError(f"Unexpected building split: {building_counts}")
    if floorplan_counts != {"train": 110, "val": 23, "test": 23}:
        raise RuntimeError(f"Unexpected floorplan split: {floorplan_counts}")

    rays = ray_offsets(config.laser_rays, config.laser_range_cells)
    manifest_rows: list[dict[str, object]] = []
    metrics = {
        "train": {"obs0": [], "obs1": [], "obs2": [], "target": []},
        "val": {"obs0": [], "obs1": [], "obs2": [], "target": []},
    }
    failed_floorplans: list[dict[str, object]] = []
    processed = [
        record
        for record in records
        if assignments[str(record["floorplan_id"])] in {"train", "val"}
    ]
    for index, record in enumerate(processed, start=1):
        floorplan_id = str(record["floorplan_id"])
        building_id = str(record["building_id"])
        split = assignments[floorplan_id]
        occupied = load_source_occupied(record, config)
        component, _ = select_navigable_component(occupied)
        starts = restricted_starts(component)
        accepted = 0
        attempts = 0
        while accepted < config.samples_per_floorplan and attempts < config.maximum_attempts_per_floorplan:
            attempts += 1
            sample_seed = stable_seed(config.generation_seed, floorplan_id, attempts)
            generated = generate_sample(
                occupied,
                component,
                starts,
                rays,
                np.random.default_rng(sample_seed),
                config,
            )
            if generated is None:
                continue
            raw_observation, raw_target, details = generated
            model_observation = cv2.resize(
                raw_observation,
                (config.model_size, config.model_size),
                interpolation=cv2.INTER_NEAREST,
            )
            model_target = cv2.resize(
                raw_target,
                (config.model_size, config.model_size),
                interpolation=cv2.INTER_NEAREST,
            )
            sample_id = f"{record['safe_id']}__{accepted:02d}"
            sample_dir = args.output_root / "samples" / sample_id
            sample_dir.mkdir(parents=True, exist_ok=False)
            raw_obs_path = sample_dir / "raw_obs_480.png"
            raw_target_path = sample_dir / "raw_target_480.png"
            obs_path = sample_dir / "local_obs_0.png"
            target_path = sample_dir / "local_map_0.png"
            Image.fromarray(raw_observation, mode="RGB").save(raw_obs_path)
            Image.fromarray(raw_target, mode="L").save(raw_target_path)
            Image.fromarray(model_observation, mode="RGB").save(obs_path)
            Image.fromarray(model_target, mode="L").save(target_path)
            manifest_rows.append(
                {
                    "sample_id": sample_id,
                    "split": split,
                    "group_key": building_id,
                    "group_kind": "building",
                    "building_id": building_id,
                    "floorplan_id": floorplan_id,
                    "source_relpath": record["source_relpath"],
                    "source_sha256": record["source_sha256"],
                    "generation_seed": sample_seed,
                    "obs_relpath": obs_path.relative_to(args.output_root).as_posix(),
                    "target_relpath": target_path.relative_to(args.output_root).as_posix(),
                    "obs_sha256": sha256_file(obs_path),
                    "target_sha256": sha256_file(target_path),
                    "raw_obs_relpath": raw_obs_path.relative_to(args.output_root).as_posix(),
                    "raw_target_relpath": raw_target_path.relative_to(args.output_root).as_posix(),
                    "raw_obs_sha256": sha256_file(raw_obs_path),
                    "raw_target_sha256": sha256_file(raw_target_path),
                    "raw_obstacle_fraction": f"{details['obstacle_fraction']:.9f}",
                    "raw_unknown_fraction": f"{details['unknown_fraction']:.9f}",
                    "raw_free_fraction": f"{details['free_fraction']:.9f}",
                    "raw_target_fraction": f"{details['target_fraction']:.9f}",
                }
            )
            for channel, key in enumerate(("obs0", "obs1", "obs2")):
                metrics[split][key].append(
                    float(np.mean(model_observation[:, :, channel] == 255))
                )
            metrics[split]["target"].append(float(np.mean(model_target == 255)))
            accepted += 1
        if accepted < config.samples_per_floorplan:
            failed_floorplans.append(
                {
                    "floorplan_id": floorplan_id,
                    "building_id": building_id,
                    "split": split,
                    "accepted": accepted,
                    "attempts": attempts,
                }
            )
        print(
            json.dumps(
                {
                    "floorplan": index,
                    "processed_floorplans": len(processed),
                    "floorplan_id": floorplan_id,
                    "split": split,
                    "accepted": accepted,
                    "attempts": attempts,
                }
            ),
            flush=True,
        )
    if not manifest_rows:
        raise RuntimeError("No train/validation smoke samples were accepted")
    manifest_path = args.output_root / "manifest.csv"
    with manifest_path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(manifest_rows[0]))
        writer.writeheader()
        writer.writerows(manifest_rows)
    summary = {
        "status": STATUS,
        "configuration": asdict(config),
        "source_root_recorded": str(args.source_root.resolve()),
        "source_split_sha256": sha256_file(source_split_path),
        "source_building_counts": building_counts,
        "source_floorplan_counts": floorplan_counts,
        "test_source_ids_frozen": floorplan_counts["test"],
        "test_samples_generated": 0,
        "test_outcomes_accessed": False,
        "generated_samples_by_split": {
            split: len(metrics[split]["target"]) for split in ("train", "val")
        },
        "generated_floorplans_by_split": {
            split: len(
                {
                    row["floorplan_id"]
                    for row in manifest_rows
                    if row["split"] == split
                }
            )
            for split in ("train", "val")
        },
        "failed_floorplans": failed_floorplans,
        "model_256_metrics": {
            split: {
                "observation_channel_white_fraction": [
                    describe(metrics[split]["obs0"]),
                    describe(metrics[split]["obs1"]),
                    describe(metrics[split]["obs2"]),
                ],
                "target_white_fraction": describe(metrics[split]["target"]),
            }
            for split in ("train", "val")
            if metrics[split]["target"]
        },
        "manifest_sha256": sha256_file(manifest_path),
        "preserved_train_only_reference": {
            "observation_channel_white_fraction_global": [
                0.01554852294921875,
                0.728926513671875,
                0.25552496337890623,
            ],
            "target_white_fraction_global": 0.09820632934570313,
        },
        "interpretation_boundary": "new declared source-aligned smoke; not an authenticated historical split, generator, trainer, or checkpoint",
    }
    write_json(args.output_root / "kth_source_aligned_smoke_summary.json", summary)
    incomplete.unlink()
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
